CREATE TABLE users
(id int(10) PRIMARY KEY AUTO_INCREMENT, 
name VARCHAR(100),
surname VARCHAR(100),
patronymic VARCHAR(100),
birth_day DATETIME);

CREATE TABLE categories 
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
parent INT(10));

CREATE TABLE tags 
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
color VARCHAR(100));

CREATE TABLE projects 
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100));

CREATE TABLE tasks
(id int(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
date_start DATETIME,
date_end DATETIME);
